version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - mariadb
    environment:
      DOCKER_ENV: "1"
    restart: always
  mariadb:
    container_name: mariadb
    image: mariadb
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./server/sql/action.sql:/docker-entrypoint-initdb.d/action.sql
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_USER: shopkeeper
      MYSQL_PASSWORD: ycjls5dm
      MYSQL_DATABASE: ntutdb
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    restart: always